# Generated by Django 5.2.7 on 2025-11-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_business",
            field=models.FloatField(default=0),
        ),
    ]
