# Generated by Django 5.2.7 on 2025-11-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="siret",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
